### ISSUE TITLE
Upgrade linux version

### ISSUE THREAD

**Issue by bess** [curationexperts/cypripedium#1]
Looks like we're on Ubuntu 16.10 right now, which is near end of life:

Welcome to Ubuntu 16.10 (GNU/Linux 4.8.0-41-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.

Your Ubuntu release is not supported anymore.
For upgrade information, please visit:
http://www.ubuntu.com/releaseendoflife

New release '17.04' available.
Run 'do-release-upgrade' to upgrade to it.

**Comment by acozine** [comment]
For now I'd recommend 16.04, which is a long-term stable release.
