### ISSUE TITLE
METADATA: Look for an alternative predicate and attribute name for isPartOf

### ISSUE THREAD

**Issue by little9** [curationexperts/cypripedium#103]
This is for the Series attribute: 

Series | isPartOf | is_part_of | ::RDF::Vocab::DC::isPartOf

This conflicts with a property in Hyrax and we should replace it with another attribute name and 
predicate.

**Comment by little9** [comment]
@janneller Since there is an issue in Hyrax currently when using dc:isPartOf, would you be OK with using schema:isPartOf for this attribute ? 

https://schema.org/isPartOf

I'm going to go ahead and use that for `Series` and if we need to change we can go back and do so. That way we can complete the terms for the importer.

**Comment by MPLSFedResearch** [comment]
shcema:isPartOf will work great, thanks.

**Comment by little9** [comment]
@janneller thanks!
