### ISSUE TITLE
METADATA: Add custom attributes to Importer

### ISSUE THREAD

**Issue by little9** [curationexperts/cypripedium#115]
This is a list of all the attributes from the spreadsheet to use as a starting point:

Attribute that are struck out are not in the current export. 
Attributes with asterisks have outstanding issues. 

- [x] Abstract
- [x] Alternative Title
- [x] ~~Bibliographic Citation~~
- [x] Contributor
- [x] ~~Corporate Author~~
- [x] Creator
- [x] ~~Date Available~~
- [x] Date Created
- [x] Date Modified*
- [x] ~~Date Submitted~~
- [x] Description
- [x] ~~Extent~~
- [x] ~~Relation: Has Part~~
- [x] ~~Relation: Is Version Of~~
- [x] ~~Relation: Has Version~~
- [x] Relation: Is Replaced By
- [x] ~~Language~~
- [x] ~~License~~
- [x] DOI*
- [x] Publisher
- [x] Relation: Replaces
- [x] Relation: Requires
- [x] ~~Resource Type~~
- [x] ~~Rights~~
- [x] Series* (isPartOf)
- [x] ~~Source~~
- [x] ~~Spatial~~
- [x] Subject
- [x] Table of Contents
- [x] ~~Temporal~~
- [x] Title

**Comment by little9** [comment]
Here's an example XML file: 

```xml
  <record>
    <title>Classical macroeconomic model for the United States, a / Thomas J. Sargent.</title>
    <creator>Sargent, Thomas J.</creator>
    <creator></creator>
    <creator></creator>
    <creator></creator>
    <contributor>Federal Reserve Bank of Minneapolis. Research Dept.</contributor>
    <subject>Rational expectations (Economic theory)--United States.</subject>
    <subject>Unemployment--United States--Statistical methods.</subject>
    <subject>Macroeconomics--Econometric models.</subject>
    <subject></subject>
    <subject>E24 - Macroeconomics : Consumption, saving, production, employment, and investment - Employment ; Unemployment ; Wages ; Intergenerational income distribution ; Aggregate human capital</subject>
    <subject>E17 - General aggregative models - Forecasting and simulation</subject>
    <subject></subject>
    <subject></subject>
    <description>Natural unemployment rate ; Montarist model ; Postwar United States ; post-1945 ; Rational expectations theory</description>
    <abstract>A statistical definition of the natural unemployment rate hypothesis is advanced and tested. A particular illustrative structural macroeconomic model satisfying the definition is set forth and estimated. The model has &quot;classical&quot;
      policy implications, implying a number of neutrality propositions asserting the invariance of the conditional means of real variables with respect to the feedback rule for the money supply. The aim is to test how emphatically the data reject a model
      incorporating rather severe &quot;classical&quot; hypotheses.</abstract>
    <tableOfContents></tableOfContents>
    <created>1975-09</created>
    <modified>2008-12-03</modified>
    <legacyFileName>19750900fedmwp22</legacyFileName>
    <relation></relation>
    <isPartOf>Working paper (Federal Reserve Bank of Minneapolis. Research Dept.)</isPartOf>
    <requires>22</requires>
    <publisher>Minneapolis : Federal Reserve Bank of Minneapolis</publisher>
    <format>PDF</format>
    <alternative></alternative>
    <alternative></alternative>
    <alternative></alternative>
    <isReplacedBy>19760400jpe8402</isReplacedBy>
    <replaces></replaces>
    <requires></requires>
    <unmapped></unmapped>
    <fullResolution></fullResolution>
    <cdmid>0</cdmid>
    <cdmaccess></cdmaccess>
    <cdmcreated>2012-03-27</cdmcreated>
    <cdmmodified>2012-03-27</cdmmodified>
    <cdmoclc></cdmoclc>
    <cdmfile>1.pdf</cdmfile>
    <cdmpath>/p16030coll1/image/1.pdf</cdmpath>
    <thumbnailURL>http://server16030.contentdm.oclc.org/cgi-bin/thumbnail.exe?CISOROOT=/p16030coll1&amp;CISOPTR=0</thumbnailURL>
    <viewerURL>http://cdm16030.contentdm.oclc.org/cdm/ref/collection/p16030coll1/id/0</viewerURL>
    <structure>http://server16030.contentdm.oclc.org/cgi-bin/showfile.exe?CISOROOT=/p16030coll1&amp;CISOPTR=0</structure>
  </record>
```

**Comment by val99erie** [comment]
@little9 I think DOI is complete.  In the XML it would be called `<identifier>`, but I think I recall someone saying that the current records don't have any DOIs, only future records will have them.  See #83.

**Comment by little9** [comment]
@val99erie I think that just leaves the Date attributes and the question about what to do with 
the legacy file name. Did they want to include that when importing? 

How do you think we should handle the dates? Make new attributes that won't interfere with the Hyrax ones?

**Comment by val99erie** [comment]
It's not necessary to store the legacyFileName because it already gets stored on the FileSet and/or File record automatically.  So, legacyFileName is also complete.

**Comment by little9** [comment]
@janneller Do you want to retain the modified date?

**Comment by little9** [comment]
@janneller `dc.dateModified` is used internally by Hyrax and will be overwritten when the work is updated or modified. We could use https://schema.org/dateModified like with `isPartOf` to retain this if we need to.

**Comment by MPLSFedResearch** [comment]
It's fine to not import the modified date from contentdm.
