### ISSUE TITLE
Configure devise password complexity to comply with FRBM requirements

### ISSUE THREAD

**Issue by bess** [curationexperts/cypripedium#12]
- [x] Configure devise password complexity to comply with FRBM requirements

**Comment by mark-dce** [comment]
See https://github.com/plataformatec/devise/wiki/How-To:-Set-up-simple-password-complexity-requirements

**Comment by mark-dce** [comment]
Or probably better, this https://github.com/phatworx/devise_security_extension

**Comment by val99erie** [comment]
Can we close this story or else add some requirements?  I'm not sure what the goal of this story is.

**Comment by MPLSFedResearch** [comment]
Sent rules to Bess on Slack, since I'm not allowed to post them to github.
Update - @val99erie what's your slack name or email address? I'll send them your way instead.
