### ISSUE TITLE
Move codebase to Federal Reserve GitHub

### ISSUE THREAD

**Issue by little9** [curationexperts/cypripedium#125]

**Comment by val99erie** [comment]
@janneller
Could you please confirm that this is the user account that we should transfer ownership of the code to:  @MPLSFedResearch 
https://github.com/MPLSFedResearch

**Comment by MPLSFedResearch** [comment]
Yes that's correct.

**Comment by val99erie** [comment]
Just to clarify - We probably won't transfer ownership until some time next week, but I just want to make sure we have all hte correct info ahead of time.

Thanks!

**Comment by val99erie** [comment]
@janneller Ok, I think we're almost ready to transfer the repo.  Before we do that, could you deploy the code to your QA environment and spend a little time making sure the features are working as you expected?  Especially check out the things we added since the last demo meeting, such as the bulk download of the zip file and the related URL field.

I tagged a release called `v1.1`, so please deploy that version to your QA, and let us know if you have any problems with the deploy or with the features.

**Comment by MPLSFedResearch** [comment]
I got an uninitialized constant error during deploy, so it failed - 
```
DEBUG [94c812f0] Command: if test ! -d /opt/cypripedium/releases/20180207173348; then echo "Directory does not exist '/opt/cypripedium/releases/20180207173348'" 1>&2; false; fi

 DEBUG [94c812f0] Finished in 0.117 seconds with exit status 0 (successful).

  INFO [1a90b29f] Running /usr/bin/env bundle exec whenever --update-crontab cypripedium --set environment=production --roles=web,app,db  as deploy@52.202.30.56

 DEBUG [1a90b29f] Command: cd /opt/cypripedium/releases/20180207173348 && ( export RAILS_ENV="production" ; /usr/bin/env bundle exec whenever --update-crontab cypripedium --set environment=production --roles=web,app,db  )

 DEBUG [1a90b29f] 	bundler: failed to load command: whenever (/opt/cypripedium/shared/bundle/ruby/2.4.0/bin/whenever)

 DEBUG [1a90b29f] 	NameError: uninitialized constant #<Class:#<Whenever::JobList:0x0000000002c2db50>>::Rails

  config/schedule.rb:34:in `block in initialize'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/job_list.rb:51:in `every'

  config/schedule.rb:33:in `initialize'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/job_list.rb:25:in `instance_eval'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/job_list.rb:25:in `initialize'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever.rb:12:in `new'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever.rb:12:in `cron'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:57:in `whenever_cron'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:111:in `updated_crontab'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:38:in `run'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:6:in `execute'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/gems/whenever-0.10.0/bin/whenever:44:in `<top (required)>'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/bin/whenever:23:in `load'

  /opt/cypripedium/shared/bundle/ruby/2.4.0/bin/whenever:23:in `<top (required)>'
```

**Comment by val99erie** [comment]
I see the same error locally when I try to run `bundle exec whenever --update-crontab`.  I'll dig around and see if I can figure out what's wrong.  Thanks!

**Comment by val99erie** [comment]
@janneller Ok, it should be fixed now.  Give it another try.  I'm going to wait to tag it until we're sure you are able to deploy it and have spent a little time testing it, so just deploy straight from `master`.

**Comment by MPLSFedResearch** [comment]
Deploying master to qa worked! I'll test it a bunch tomorrow morning and let you know how it goes.

**Comment by MPLSFedResearch** [comment]
So far things are working as expected, except the zip file download is taking longer than I'd think. I'm on minute 20 of a zip file of 2 PDFs. I've refreshed a few times. This record: [http://52.202.30.56/concern/publications/nc580m68d?locale=en](url).  I checked sidekiq and it looks like the the ```BuildWorkZipJob``` is not working, sending ```NameError: uninitialized constant #<Class:0x000000000799db10>::Zip```.  

There's also a ```StreamNotificationsJob``` error: ```Gem::LoadError: Specified 'redis' for Action Cable pubsub adapter, but the gem is not loaded. Add `gem 'redis'` to your Gemfile (and ensure its version is at the minimum required by Action Cable).```

**Comment by little9** [comment]
@val99erie @bess Could the first error be some issue with auto loading in development vs production? 

The second error might be a red herring, but redis might need to be installed on the server? I don't remember reading any `ActionCable` bits in that zip pr 🤔

**Comment by val99erie** [comment]
Yeah, something is wrong, probably with the class loading, as Jamie suggested.  On my laptop it takes less than a minute to build a zip with a few files.  I'll dig around today and see if I can figure anything out.

**Comment by val99erie** [comment]
Ok, with the new changes, I think we're almost ready to go.  I made a new tag `v1.2`.  I'm going to check with my team once more to make sure there's nothing left, and I'll start the transfer a little later today.
