### ISSUE TITLE
Clean up temp space on server

### ISSUE THREAD

**Issue by little9** [curationexperts/cypripedium#126]
Create a cron job to clean up temp files.

**Comment by bess** [comment]
See https://github.com/curationexperts/playbook/pull/41

**Comment by val99erie** [comment]
In addition to the normal hyrax temp file cleanup, please also write a cleanup task for the work zip files.  See story #127.

The code that decides where to put the zip files is this:
`ENV["CYPRIPEDIUM_ZIP_DIR"] || Rails.root.join('tmp', 'zip_exports')`

So, if you set the environment variable `CYPRIPEDIUM_ZIP_DIR`, it will put the files there.  But if you don't set the env var, it will put them in the default location under your Rails root: `tmp/zip_exports`

- [ ] Write a task to clean up zip files in this directory that are too old.  (We had talked about cleaning files older than 7 days, for example).
