### ISSUE TITLE
Collections aren't displaying their members in the UI

### ISSUE THREAD

**Issue by little9** [curationexperts/cypripedium#128]

**Comment by val99erie** [comment]
I don't think I'm going to have time to do this story before the weekend.  Just in case anyone picks it up before me, here's a clue...

If you add the collection id to the solr index for the work using key `member_of_collection_ids_ssim`, then that work will appear on the collection's show page.
https://github.com/samvera/hyrax/blob/master/app/search_builders/hyrax/collection_member_search_builder.rb#L8

So, in the importer, we can probably just do something like this before we save the work:
`work.member_of_collections << collection`
