### ISSUE TITLE
Annotations accepted criteria

### ISSUE THREAD

**Issue by MPLSFedResearch** [curationexperts/cypripedium#134]
I have more detail on what we are looking for with the "annotate external references" work. We'd like a way to enter the related URL, and then have some optional free text area that goes with the URL where we can say "Summary version" or "Journal of Economic Literature edition".  Many of our works will have multiple related URLs. Our publications are pre-prints, and the same work ends up being published in multiple places: a journal, an annual review, an encyclopedia. Some also have shorter summary papers meant for public consumption.  If there are four related URLs, and 3 are DOIs, it is hard for the end user to make sense of each URL without additional context.

**Comment by little9** [comment]
@MPLSFedResearch do you think that if we change the Related URL element to a multiline text entry that would suffice instead of a single line? Hyrax doesn't have these kind of controls by default and we'll need to create some custom JavaScript to handle this. Let me know your thoughts. We can also change the help text under Related Url to give some instructions on how to fill it out.

**Comment by MPLSFedResearch** [comment]
Multiline text entry would work. Could the URLs be hyperlinked or would the staff be inserting html themselves?

**Comment by little9** [comment]
@MPLSFedResearch Let me check and I'll get back with you

**Comment by little9** [comment]
@MPLSFedResearch Let me know if this would be OK for this story. We changed the text box for the Related URL entry to a textarea so you can input more text into the field comfortably and added the ability to write Markdown in that field. That way your users can enter URLs like this:

```markdown
[Link Text](http://url_here.com) Explanatory text
```

If they forget and just add a URL, that will be autolinked:

```markdown
http://url_here.com Explanatory text
```

and you can just use HTML in that field.

In the help text we can put a link to instructions on how to make links in Markdown: https://daringfireball.net/projects/markdown/syntax#link and an example for link. 

Let me know if this is an acceptable solution for this story. 

Here's what the UI will look like:

![screenshot-2018-2-7 new publication research database](https://user-images.githubusercontent.com/4324761/35922000-f1871a90-0be1-11e8-882f-da9eadb97a98.png)

**Comment by MPLSFedResearch** [comment]
This looks perfect, thanks!
