### ISSUE TITLE
Download notification

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#192]
**STORY**
As a librarian, I’d like to be notified when my bags are ready for download.

**DETAILS**
Unless there's an easier option, we should use Hyrax's native notification system (both in-browser and e-mail) to deliver user notifications.

**ACCEPTANCE**
When I'm logged in
- [ ] When my bagit export is done, I get an in-browser notification

**Comment by mark-dce** [comment]
As an example, when I export incident tickets from FreshDesk, which gets processed in the background, I get a flash message like this in the browser:
>Your Ticket data will be sent to your email shortly!  
 
&nbsp;  
 
Followed by an e-mail sometime later like this:
>Hi Mark Bussey, 
>
>The ticket export you had requested is complete. You can download the file from here. If the link does not work, copy and paste the URL below in your browser's address bar: 
>
>https://curationexperts.freshdesk.com/download_file/2/05a99356b2bedd455964fbd310ea238186150040 
>Note: This link will expire in 15 days. 
>
>Regards, 
>Data Curation Experts Support

**Comment by mark-dce** [comment]
This is marked as ready for review.  Is there anywhere I can login and see the in-browser notification?
