### ISSUE TITLE
SPIKE: Sample Data

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#202]
SPIKE: Populate DCE environment with test data
**ACCEPTANCE**
We can populate a test environment with
- [x] 10-20 works
- [x] 2 collections exist with 4-6 works
- [x] 2 collections exist without any works
- [x] 1 Admin set exists

**Comment by mark-dce** [comment]
Ideally we'd have a repeatable task that populates a knows set of data on new environments.  This way, if we discover any problem content at any time, we can add it to the sample set as edge cases.
