### ISSUE TITLE
PAIRING: Sort within Collections by Title

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#205]
**STORY**
As a researcher, I want to be able to sort collection results by Title

**ACCEPTANCE**
- [x] On a collection page (like https://researchdatabase.minneapolisfed.org/collections/2j62s4898?locale=en) I have the option to sort results within the collection by Title

Child of #189

**Comment by val99erie** [comment]
Note: Existing records will need to be re-indexed in order to sort by title.
