### ISSUE TITLE
PAIRING: Sort by Date Created

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#208]
**STORY**
As a researcher, I would like to be able to sort search results by their creation date, so that I can search for recent and historical information easily.

**ACCEPTANCE**
- [x] The "Sort by" dropdown on search results includes "Date Created" ascending and descending as options

child of #189

**Comment by mark-dce** [comment]
Child of #189

**Comment by RachelDCE** [comment]
Child of #189

**Comment by val99erie** [comment]
You'll need to reindex existing records before you can use the sort.  The sort appears in the UI as "Date published"

**Comment by mark-dce** [comment]
👍 
<img width="823" alt="screen shot 2018-11-29 at 10 51 15 am" src="https://user-images.githubusercontent.com/3064318/49238011-23d3f380-f3c5-11e8-9df1-86ace08d90be.png">
