### ISSUE TITLE
PAIRING: Remove Date Modified on sort

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#209]
**STORY**
As a researcher, I don't want to see a date modified sort option, because it's clutter I don't really need.

**ACCEPTANCE**
- [ ] The "Sort by" dropdown on search results *does not* list "Date Modified" ascending or descending as options

Child of #189

**Comment by mark-dce** [comment]
Child of #189

**Comment by MPLSFedResearch** [comment]
Leaving date modified sort for future need to sort this way with incoming publications. Closing. 

Connected to #209
