### ISSUE TITLE
PAIRING: Remove Date Uploaded on sort

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#210]
**STORY**
As a researcher, I don't want to see a date uploaded sort option, because it's clutter I don't really need.

**ACCEPTANCE**
- [x] The "Sort by" dropdown on search results *does not* list "Date Uploaded" ascending or descending as options

Child of #189

**Comment by mark-dce** [comment]
Child of #189

**Comment by mark-dce** [comment]
👍 Looks good - here's what I'm seeing on https://cypripedium-cd.curationexperts.com

<img width="823" alt="screen shot 2018-11-29 at 10 51 15 am" src="https://user-images.githubusercontent.com/3064318/49237855-cb9cf180-f3c4-11e8-8563-8d65ce992669.png">
