### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#212]
**STORY**
As an engineering manager, I want to know that I have adequate test coverage, so that my upgrades have minimal risks

**DETAILS**
Coverage is currently at 84%, which feels like it might be a little low - https://coveralls.io/github/MPLSFedResearch/cypripedium?branch=master

**ACCEPTANCE**
- [x] The team agrees on a standard for test coverage - _we use % only as a guide and evaluate the relative risk of code not covered by tests_
- [x] We do a time-boxed review of the code that is not covered and generate tickets for any portions that are high risk

**Comment by little9** [comment]
@mark-dce  @bess  @val99erie 

The biggest hit on coverage in this repo 

Is from this: https://github.com/MPLSFedResearch/cypripedium/blob/master/app/services/hyrax/file_set_derivatives_service.rb

https://coveralls.io/builds/20343897/source?filename=app%2Fservices%2Fhyrax%2Ffile_set_derivatives_service.rb

It is an override, but I'm not sure what it is supposed to fix.

There are also a bunch of Rails auto-generated files that I think we should
ignore with simplecov configuration:

https://coveralls.io/builds/20343897/source?filename=app%2Fmailers%2Fapplication_mailer.rb

https://coveralls.io/builds/20343897/source?filename=app%2Fchannels%2Fapplication_cable%2Fconnection.rb

and so on. Those will be in every Rails project. We can use a simplecov config like the one that I did for ursus and just ignore them:

https://github.com/UCLALibrary/ursus/blob/master/.simplecov
