### ISSUE TITLE
Set up cypripedium-cd server for continuous deployment

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#222]
**ACCEPTANCE**
- [x] We have a new environment set up for continuous deployment
- [x] Master gets deployed to cypripedium-cd on new commits

**Comment by bess** [comment]
I can confirm that the master branch is now deploying to cypripedium-cd whenever it passes CI on travis. Screen shot of the most recent deploy from Travis attached.

See https://cypripedium-cd.curationexperts.com

![travis_ci_cypripedium.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46fc869b358b90968ce08040bd4de29d3943237a3c09e1673295f127b54778154d555ca9480c5b44fff8df2eafe33d778d5c0bef87695627c56e15bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8b4c3c18001d8afc5c32a38b06.png)

**Comment by mark-dce** [comment]
Verified that the most recent commit is deployed to cypripedium-cd

<img width="1044" alt="screen shot 2018-11-26 at 1 05 31 pm" src="https://user-images.githubusercontent.com/3064318/49042367-9ce90600-f18d-11e8-96dc-9b4cca0dfd78.png">


<img width="536" alt="screen shot 2018-11-26 at 1 08 38 pm" src="https://user-images.githubusercontent.com/3064318/49042368-9d819c80-f18d-11e8-995e-59c9181018df.png">
