### ISSUE TITLE
E-mail notifications

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#223]
**STORY**
As a librarian, I’d like to be notified **by email** when my bags are ready for download.

**ACCEPTANCE**
When e-mail notifications are configured (and my id has an e-mail associated)
- [ ] When my bagit export is done, I get an e-mail

**Comment by little9** [comment]
@mark-dce @bess 

This will work if ActionMailer is configured, but it requires that sendmail is set up on the server, or some smtp credentials are setup in the environment: 

https://guides.rubyonrails.org/action_mailer_basics.html#example-action-mailer-configuration

* Do we know if MPLSFed has sendmail installed on the server? 

* If we wanted to use an smtp account we would need a way of deploying a password 
with an env variable on that server.

**Comment by mark-dce** [comment]
I just heard back from Janelle  and we don't need to test e-mail right now since they're not using it.

>Q: Do you have e-mail notification set up and should folks be notified by e-mail when their export is ready for download? - see E-mail notifications #223 - we won’t bother with this if you don’t have e-mail notifications configured, you’d need to have the mailer on your server setup and configured for Hyrax.  Let me know if you want to talk about this more
>
>A:  We don’t have email configured and due to security rules probably never will. Since we’re a small staff, I think the person who will be using this can remember to check. If/when this expands to other Feds I may figure out a way to let the email server set up.
