### ISSUE TITLE
Intermittent spec failure (mkdir)

### ISSUE THREAD

**Issue by val99erie** [curationexperts/cypripedium#253]
Failures:

  1) BagController POST #create redirects after the request
     Failure/Error: FileUtils.mkdir(bag_path)
     
     Errno::EEXIST:
       File exists @ dir_s_mkdir - /Users/valerie/valerie/work/dce/projects/fed_reserve/cypripedium/tmp/bags
     # ./spec/controllers/bag_controller_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 1 minute 54.2 seconds (files took 36.96 seconds to load)
148 examples, 1 failure

Failed examples:

rspec ./spec/controllers/bag_controller_spec.rb:26 # BagController POST #create redirects after the request

Randomized with seed 8005

**Comment by little9** [comment]
Fixed in this commit: 

https://github.com/MPLSFedResearch/cypripedium/commit/84e6e5ecc095f2dfcfb312bd172137e63865fd89
