### ISSUE TITLE
Feature collections on home page

### ISSUE THREAD

**Issue by val99erie** [curationexperts/cypripedium#256]
- [x] There is a way to decide which collections are shown on the home page.
- [x] I can control which order the collections appear in the list.

**Comment by val99erie** [comment]
For review/demo:  The collections that should appear on the home page are these:

'Working Papers Archive',
'Conference Proceedings Archive',
'Research Data',
'Warren E. Weber Historical Data Archives',
'Antebellum U.S. State Bank Balance Sheets'

**Comment by mark-dce** [comment]
![256 - featured collections](https://user-images.githubusercontent.com/3064318/49672417-a77a8980-fa30-11e8-9353-9cb1c52b85b6.png)
