### ISSUE TITLE
Allow markdown in description field for collections

### ISSUE THREAD

**Issue by val99erie** [curationexperts/cypripedium#257]
- [x] When editing a collection record, I can add markdown in the description field.
- [x] When the collection record is displayed, the markdown is rendered properly.

**Comment by mark-dce** [comment]
Looks good to me

<img width="715" alt="257 - markdown in description" src="https://user-images.githubusercontent.com/3064318/50027464-fdf84280-ffb1-11e8-857a-f1be6e9324da.png">

**Comment by mark-dce** [comment]
Sorry, I'm just seeing that we don't render the markdown in the search results view, I think we need to do that too?

<img width="581" alt="257 - markdown in search results not rendered" src="https://user-images.githubusercontent.com/3064318/50027696-c1791680-ffb2-11e8-92ae-7109d4d57fc0.png">

**Comment by mark-dce** [comment]
Hmm, I can't get the system to reproduce the above and things are rendering as expected now.

**Comment by mark-dce** [comment]
@janneller We've got markdown mostly working, but there are some conflicts occurring between the hyrax code that ensures safe HTML and the code that enables markdown.  You can add headings, bold, italics, and links to descriptions, but not block quotes or bullet lists.  Take a look at this collection and let us know if this is ok or if you need the missing items to work:
https://cypripedium-cd.curationexperts.com/catalog?utf8=✓&locale=en&search_field=all_fields&q=markdown

**Comment by MPLSFedResearch** [comment]
Headings, bold, italics and links will suffice, thanks.
