### ISSUE TITLE
Not all selected items exported

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#260]
**ISSUE**
When I select multiple items, not all items are actually being exported.

**STEPS TO REPRODUCE**
1. Login as an administrator
1. Go to the "All Works" tab
1. Select two or more items to export
1. Choose "Add to Bag"

NOTE: It looks like some works may just not be exporting at all...

<img width="914" alt="260 - 5 items for export" src="https://user-images.githubusercontent.com/3064318/49534884-59c31d00-f888-11e8-911b-8fdefcf961eb.png">

<img width="1415" alt="260 - additional item count is incorrect" src="https://user-images.githubusercontent.com/3064318/49534897-5def3a80-f888-11e8-887c-7ead76d6b574.png">

<img width="775" alt="260 - actual export contents" src="https://user-images.githubusercontent.com/3064318/49534905-6182c180-f888-11e8-9119-84d2f3ded38e.png">

**Comment by mark-dce** [comment]
Ok - I think I figured this one out - we're not getting anything exported because there's no file attached to two of the works.  We can put this on the back-burner and retest once we're exporting metadata #265 if we want.

**Comment by RachelDCE** [comment]
Blocked by #265

**Comment by mark-dce** [comment]
Looks like we get the expected folders now that we also export metadata
