### ISSUE TITLE
PAIRING: Assist Janelle with Infrastructure upgrades

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#264]
**ACCEPTANCE**
- [x] MPLSFed AWS instances upgraded to Hyrax 2.4.1 release of cypripedium
    - [x] QA
    - [x] Staging
    - [x] Production

**Comment by bess** [comment]
QA and Staging are done. We're going to do production Wednesday morning.

**Comment by bess** [comment]
Production is upgraded. We identified a couple of places for future improvement:
1) Automating backups
2) Putting EC2 instances on elastic IPs so their IP addresses don't change when they restart
I've opened tickets for both these.

The upgrade itself went fine.
