### ISSUE TITLE
Can't add new content via UI

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#276]
**ISSUES**
I'm no longer able to add a new item to the repository via the user interface.  I was definitely able to create two items successfully prior to the upgrade.

**STEPS TO REPRODUCE**
1. Login (use an administrator account to see sidekiq errors in future steps)
1. Visit the "Your Works" tab on the dashboard
1. Click the "Add new work" button
1. Choose "Publication" as the work type and click the "Create new work" button
1. Give the work a title, attach a file, check the deposit agreement, and click the "Save" button

**EXPECTED RESULT** 
My new work appears with a thumbnail of the file I attached.

**ACTUAL RESULT**
The work appears, but there is no thumbnail associated, and multiple jobs are retrying due to errors in Sidekiq (i.e. check out https://cypripedium-cd.curationexperts.com/sidekiq/retries)

**ACCEPTANCE**
- [ ] I can create new works via the UI with files correctly attached

![276 - cant add new works](https://user-images.githubusercontent.com/3064318/49671436-7cdb0180-fa2d-11e8-9515-8d5e3eef7b61.png)

**Comment by val99erie** [comment]
Some more clues:

* I cannot reproduce on my dev environment.  When I create works using the UI, thumbnails appear correctly.

* I also cannot reproduce the problem on the QA environment.

* I did see the problem on the CD environment for a few minutes, but it eventually succeeded with retries.

So, I'm guessing this isn't necessarily related to Hyrax upgrade, but either an issue with the environment (maybe QA is provisioned differently than CD), or more likely, something is in a bad state.

I hate to suggest "Have you tried turning it off and on again?", but I wonder if restarting sidekiq would help?

**Comment by val99erie** [comment]
I asked Jamie to restart sidekiq on CD server.

**Comment by val99erie** [comment]
CD environment seems to be working properly after restarting Sidekiq.

@mark-dce I'll pass the story back to you

**Comment by little9** [comment]
@mark-dce is this OK now?
