### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#296]
**ACCEPTANCE**

- [x] Make s snapshot of production
- [x] Export all data from a snapshot of production  
- [x] Import it all into newly built system
- [x] There should be the same number of objects
- [x] Swap out new system for production system

**Comment by bess** [comment]
FYI: Jannelle says we can capture the production backup whenever we like:
```
Bess Sadler [4:59 PM]
When would be an okay time to restart the production instance so we can get a snapshot for data migration?

Jannelle Ruswick [4:59 PM]
Whatever works for you, 4 minutes isn't a big deal.
```
