### ISSUE TITLE
Collections inaccessible on prod and staging

### ISSUE THREAD

**Issue by MPLSFedResearch** [curationexperts/cypripedium#328]
When a user clicks on a collection in prod or staging, they get a "We're sorry, something went wrong." This happens when clicking on the collection on the home page or from clicking on collection in search/browse. QA is unaffected. Works are unaffected.

**Comment by bess** [comment]
The problem was that Fedora wasn't running. Looks like it ran out of memory:

```
INFO 23:55:35.796 (FedoraLdp) HEAD for: prod/bv/73/c0/43/bv73c043w
INFO 23:55:35.798 (FedoraLdp) GET resource 'prod/bv/73/c0/43/bv73c043w'
INFO 23:55:36.054 (FedoraLdp) HEAD for: prod/bv/73/c0/43/bv73c043w
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f75597c4000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 12288 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1390.log
[thread 140142121424640 also had an error]
```

I will adjust the memory settings for it and also add some configuration so that if it crashes it will restart on its own.

**Comment by bess** [comment]
After restarting Fedora everything seems fine. I'll make a separate ticket to track the memory issue and auto-restart.
