### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#330]
**STORY**
As a repository manager I want users to be able to access the site without being negatively impacted by bots or other automated services crawling the site. 

Note: We still want to allow Google etc to index the site.

**ACCEPTANCE**
- [x] Interactive response time does not degrade when the site is being indexed
- [x] Content in the site is still accessible to crawlers

**Comment by RachelDCE** [comment]
We think we can do this with the Apache QOS module

**Comment by little9** [comment]
Here's an example of the rate limiting they are doing already via Amazon WAF:

![Screenshot_2019-03-15 CloudWatch Management Console.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589de7daddc0c81a00399ded/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd6416743e7851e3087c8af62c88436f02074f33fd1f090811a1acd76fb6c5632ec90357b8c3714d3484624bf9ebc60db513bf29df4b85b5bddc49c9bd3c22e08b8f4d681a0c4b8aac5927bc8b099906a214bc141ff1512469f4773e7646911b772a6d6224adf9da5081972d.png)

The orange lines on the graph represent traffic that's been protected with the http flood protection rule.
