### ISSUE TITLE
Schema.org microdata not showing for some fields

### ISSUE THREAD

**Issue by MPLSFedResearch** [curationexperts/cypripedium#367]
Displaying Schema.org microdata is enabled in cypripedium. Some tools, such as [Google Dataset Search](https://datasetsearch.research.google.com/), require specific schema.org fields in order for our content to be included. 

There are fields that need schema.org markup but are not getting it. [This example](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fresearchdatabase.minneapolisfed.org%2Fconcern%2Fpublications%2Ftb09j581r) shows in the Structured Data Testing Tool what fields have correct markup.

**Federal Reserve Bank of Minneapolis**
Repository website: https://researchdatabase.minneapolisfed.org
Codebase: https://github.com/MPLSFedResearch/cypripedium

The following fields need schema.org markup applied: 
- [x] Creator
- [x] Abstract
- [x] Description
- [x] Identifier

Fields that would be nice to have, but only if the work isn't too onerous: 
- [ ] ~Series~ series is not a schema.org attribute of a CreativeWork
- [ ] Issue Number
- [x] License

**Comment by fnibbit** [comment]
"Series" is not recognized by google as an attribute of "CreativeWork", will require more research to find out correct markup.

**Comment by fnibbit** [comment]
Series and Issue number are not attributes of CreativeWork, using a more specific schema.org item type would be a larger piece of work.
