### ISSUE TITLE
Change default sort 

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/cypripedium#368]
Client would like to change how works are sorted on a collection page. She would like them default sort to issue number descending.

**Federal Reserve Bank of Minneapolis**
Repository website: https://researchdatabase.minneapolisfed.org
Codebase: https://github.com/MPLSFedResearch/cypripedium

**Comment by bess** [comment]
![Screen Shot 2020-06-19 at 3.04.02 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/bdaa0a7b-7464-400a-a7e8-bb9388a0137e)
