### ISSUE TITLE
Update Gems

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#371]
**ISSUE**
While we are focusing attention on Cypripedium, we should identify any gems that are candidates for upgrade - even if they do not specifically include security vulnerabilities.

**BACKGROUND**
https://thoughtbot.com/blog/keep-your-gems-up-to-date

**Federal Reserve Bank of Minneapolis**
Repository website: https://researchdatabase.minneapolisfed.org
Codebase: https://github.com/MPLSFedResearch/cypripedium

**ACCEPTANCE**
Time-box initial analysis and updates to 4 hours
- [x] Run `bundle outdated`
- [x] Update as many outdated gems as possible - start with patch versions, then minor, then major
- [x] Research any outstanding outdated gems and write a ticket for each that presents any significant outstanding risk (deprecation of key features in future releases, etc.)

**Comment by bess** [comment]
Tickets written in support of this ticket: 

https://github.com/MPLSFedResearch/cypripedium/issues/381

**Comment by bess** [comment]
I have spent four hours on this and I think fixing this active-fedora bug is going to be the most important thing to address.

Update: FIXED!
