### ISSUE TITLE
Address deprecation warnings

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#372]
**ACCEPTANCE**
Time-box analysis and updates to 4 hours
- [x] Identify deprecation warnings during CI / local test suite runs
- [x] Identify deprecation warnings during boot
- [x] Address as many as possible
- [x] Write up tickets for any outstanding deprecations that present serious risk (i.e. significant development effort to address in the future)

**Federal Reserve Bank of Minneapolis**
Repository website: https://researchdatabase.minneapolisfed.org
Codebase: https://github.com/MPLSFedResearch/cypripedium

**Comment by bess** [comment]
Addressed deprecation warning for browse_everything. All other warnings are internal to hyrax and there is nothing actionable for us to do. 

UPDATE: The fix for browse everything didn't work as advertised, so I made a ticket: https://github.com/MPLSFedResearch/cypripedium/issues/392
