### ISSUE TITLE
Ensure new DCE team members have access to all Environments

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#416]
**ACCEPTANCE**
- [x] Update authorized keys on 
   - [x] researchdatabaseqa.minneapolisfed.org 
   - [x] researchdatabasestaging.minneapolisfed.org 
   - [x] researchdatabase.minneapolisfed.org 
- [x] Ensure current working team has ssh access
   - [x] Mark
   - [x] Rachel K
   - [x] Max
- [x] AWS CLI and UI credentials
  - [x] Rachel K
  - [x] Max
  - [x] Mark

**Comment by maxkadel** [comment]
Max can SSH to all 3 environments. Rachel K. is getting a timeout. Based on Max's SSH'in in, Rachel's keys are on the servers, and she's not getting an access denied message, but an actual timeout, so it's probably some other configuration, possibly permissions for what IP addresses are allowed to SSH in from, configured on AWS.

**Comment by maxkadel** [comment]
Turns out I can't ssh from home! Dang it! So it'd be cool if my (new) home IP could be added too.
