### ISSUE TITLE
Merge and release outstanding dependabot PRs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#417]
**ACCEPTANCE**
- [x] Merge outstanding dependabot PRs
- [x] Cut a new release
- [x] Deploy to 
   - [x] QA
   - [x] Staging 
   - [x] Production

**Comment by maxkadel** [comment]
v4.2.2 released

Master deployed to QA, having trouble remembering magic incantation to get Cap to deploy a specific version.

**Comment by maxkadel** [comment]
QA - ![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/226d37d0-dee6-4e47-8594-fa6352d0a912)

**Comment by maxkadel** [comment]
```
$ BRANCH_NAME=v4.2.2 bundle exec cap staging deploy
. . .
Caused by:
Net::SSH::AuthenticationFailed: Authentication failed for user deploy@18.211.59.195

Tasks: TOP => deploy:check => git:check => git:wrapper
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@18.211.59.195: Authentication failed for user deploy@18.211.59.195
```

I can ssh in as myself, but not as the deploy user. When I look at my groups, I am in the deploy group. I tried changing the user in `config/deploy/staging.rb` to `max` and got significantly further, but then had permissions issues (the max user has sudo privileges but has to actually invoke them). 

I'm not sure if this is an Ansible role that needs to be run?
