### ISSUE TITLE
SPIKE: Gather Creator Sample Data

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#418]
**ACCEPTANCE**
Create a sample table (google doc is fine) with
- [x] 5-25 Creator records representing examples from the live dataset
- [x] Include data for the fields in the object model
     - [x] Last Name
     - [x] First Name
     - [x] Alternate name(s)
     - [x] Affiliation
     - [x] Repec ShortID
     - [x] Active (true/false)

**Comment by mark-dce** [comment]
More background: 
* RePEc IDs - You can look up the creator name here: https://ideas.repec.org/i/e.html; the "Personal Details" section for an individual should have the short ID https://ideas.repec.org/e/pbu47.html - I'm not sure whether all FRBM creators are guaranteed to have a RePEc Entry.  More background here https://ideas.repec.org/t/shortid.html
* Affiliations - Can also be found in the RePEc Author Information site under the "Affiliation" section for an individual record: https://ideas.repec.org/e/pgh181.html
* All the names in the current repository are active - inactive is a new concept being introduced to accommodate deduplication and record mergers going forward.

**Comment by fnibbit** [comment]
Have gathered names from live site (top ten plus a sampling of name-patterns I saw paging through).  Halfway through grabbing IDs+affiliations from RePEc.

**Comment by fnibbit** [comment]
https://docs.google.com/spreadsheets/d/1RXdeuMzUoYIU5-iQB15X8Ve1_otBAzXrE_e72FnGQNE/edit?usp=sharing

**Comment by fnibbit** [comment]
Did not find RePEc entries for Soo-Nam Oh and Preston J. Miller.  Took extra tries to find Mariacristina De Nardi because the RePEc search wants you to enter at least three letters of the beginning of the "last name" *and* hates spaces.

**Comment by MPLSFedResearch** [comment]
Is it too late to request changes to the fields? It's been some time since the initial project request, and I have a clearer picture now. 

- [ ] Keep the creator name as one field, so just like you see the creator field now and not split between First and Last. 
- [ ] We aren't planning on managing affiliations anymore, so we can remove that.
- [ ] Instead of an affiliations field, we'd like a field for the VIAF ID just as a string. I know integration is out of scope, but having the ID is helpful for any future plans. 

I can complete the data for the fields in the sample file if you are able to give me editing access. Hope this isn't a hassle!

**Comment by mark-dce** [comment]
We should pint out the differences between RePEc practices - i.e. ignore spaces in "last name" and Hyrax practices - i.e. include spaces and punctuation in lexical sorts.  I think it will be ok to stick with Hyrax defaults, but we should call it out.

| RePEc | Hyrax |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/3064318/113050312-4da2ae00-916a-11eb-85f7-06f2d083720d.png)|![image](https://user-images.githubusercontent.com/3064318/113050699-bee26100-916a-11eb-829f-c5ca87b3f52b.png) |

**Comment by MPLSFedResearch** [comment]
For the repec ID, there is a 'short ID' that we'll be using. [Repec Short-ID lookup](https://ideas.repec.org/cgi-bin/shortid.cgi), so there won't be any spaces. For example, pde51 will be what you would see in that field.

**Comment by fnibbit** [comment]
I've added you as an editor for the sample data file.  Thanks!
