### ISSUE TITLE
Add a new Creator authority record

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#420]
**STORY**
As a librarian, I want to be able to create a new creator record, so that I have an authoritative record that I can associate with works in the repository.

**ACCEPTANCE**
- [x] I can create a new creator record with
    - [x] A unique ID [required, unique, non-repeating]
    - [x] A creator display name [required, non-unique, non-repeating]
    - [x] An optional list of alternate names [optional, non-unique, repeating]
    - [x] An optional RePEc ID [optional, unique, non-repeating]
    - [x] An optional VIAF ID [optional, unique, non-repeating]
- [x] We document any assumptions we make to make this ticket implementable

**QUESTIONS**
* Which, if any, fields are required - `ID` & `Display Name`

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/c639e318-3d79-4bf8-88dd-8f065f3f6750)  on branch creator_record 
Still WIP (views+controllers are still template-out-of-the-box).  Serialized alternate_names using " ; " as a separator, screenshot is the result of cut+pasting the first few entries from the frbm sample spreadsheet into the "new creator" form.

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/82cd2216-def1-4366-aa29-195e4064214c) when logged in

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/2e3d51f1-0af3-41cf-8f63-e3526516379e) when logged out
