### ISSUE TITLE
Display Creator Records

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#422]
**STORY**
As a librarian, I would like to be view existing creator records, so that I can determine if a creator record already exists or whether I need to create a new one.

**ACCEPTANCE**
- [x] Admins see a link on the dashboard for "Manage Creators"
- [ ] The link displays a paginated table of creator records
- [ ] [BONUS] I have search, sort, and filter controls

**DESIGN NOTE**
We need to figure out if there's any reason not to use datatables for this.  They're already used for the works and collections views, so they extend a user interface the librarians are already familiar with.

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/7d77480a-cb1b-46d9-9c10-80bb8111d0b9) non-paginated/non-datatables version running locally with 888 entries loads in just under 4 seconds.

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/3f66764e-04f7-4882-b54f-a853f2c51e31)
less ugly
