### ISSUE TITLE
Associate one or more creator records with a work - Create & Edit

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#423]
**STORY**
As a librarian, I would like to be able to associate a creator record with a work, so that I have consistent data across works and can easily update creator data for all associated works.

**ACCEPTANCE**
When I create or edit a work
- [x] I can enter a partial creator name and the system will show me potential matches
    - [ ] ~Potential matches should include alternate names~ - de-scoped
- [ ] When I select a matching name, the system stores the associated creator record ID
- [ ] The system uses the primary display name for display, faceting, and viewing
- [ ] The system searches for creator matches against ~both~ primary display name ~and alternate names~
   - [ ] I can do a search against a partial display name

**DESIGN QUESTIONS**
* Do we overwrite the existing creator attribute, or leave it in place and add a new attribute for controlled-creator links?
   * Further thoughts: keep the current attribute for the primary display name and add an attribute for the ID - this makes it easy to know what to display on show views, but gives us access to the creator by ID so that we can access the full creator record for tokenizing and indexing both the primary and any alternate names
* Do we store the local ID or a full URI

**Comment by maxkadel** [comment]
Thoughts
For the second point (storage) - do we mean solr & fedora? Just one or the other?

**Comment by mark-dce** [comment]
I'm thinking we only need to store the ID in Fedora - this avoids conflicts of having ID vs. string mismatches.  
AND  
We'll need to index the name into Solr so that we can search and facet on it.  I have a bias toward indexing more rather than less into Solr, so I'd also lean toward indexing the ID into solr so we can use ad-hoc search and queries to diagnose problems more easily.  

WORKS: when we update a single work to add or change a creator, save the updated ID(s) to Fedora, re-index the display names and IDs to Solr.
CREATORS: when we update a creator record, search (solr query?) works by the creator ID, re-index all the associated works with the updated creator information

**Comment by mark-dce** [comment]
Superseded by #453 & #454
