### ISSUE TITLE
Update creator records

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#424]
**STORY**
As a librarian, I would like to be able to update an existing creator record, so that I can incorporate changes like name changes (or corrections) additional alternate names, updated birth or death dates, etc.

**ACCEPTANCE**
- [x] I can select an existing creator record to edit from the list of creators available from the dashboard (see #422)
- [x] I can edit any field _EXCEPT_ the primary record ID
- [x] When I save changes, all works pointing at this record are reindexed with any new information

**DESIGN NOTES**
* Do the work reindex in real-time/inline for this ticket, we'll handle the background job as a separate ticket

**Comment by fnibbit** [comment]
Look out for the serialization of the alternate names -- template-generated edit form winds up mushing them together.

**Comment by fnibbit** [comment]
On my dev environment: from console, assigned pub.creator_id = [ActiveTriples::Resource.new('http://localhost:3000/authorities/show/creator_authority/887')]

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/3f197f85-055f-4d03-863a-930c3bc780d3)

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/d10ddd40-3f10-4aa4-aee6-18c229d37d29)

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/c76532c0-839c-42aa-93a8-f68ab7ca0481)

**Comment by fnibbit** [comment]
https://github.com/MPLSFedResearch/cypripedium/pull/474 branch deployed to QA.
