### ISSUE TITLE
Disable a creator record

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#427]
**STORY**
As a librarian, I want a mechanism to address when I accidentally create duplicate author records.

**ASSUMPTION**
Implementing a full record merge function is beyond the scope of this engagement, so we'll provide a manual means to disable a record so that it cannot be associated with any new records.  A manual merge would entail identifying the old creator record to be eliminated, disabling it, and then updating all works associated with the old creator record to point to the new creator record.

**ACCEPTANCE**
- [x] Librarians can disable a creator record (persisted to the creator record in the DB)
- [x] When a creator record is disabled, it will not appear in the creator suggestion list for new works or when editing works (reflected in the authority endpoint)
- [x] When editing a work with a disabled creator, it can be saved with a disabled creator id if the creator reference has not been changed
- [x] When displaying an existing work with a disabled creator record, the displayed work is not changed.

**NOTE**
The UI for this might just look like a checkbox that say "Active" that is on by default when we make a new creator.

**Comment by mark-dce** [comment]
Hyrax Creative Commons rights statement might be a good place for examples of how this is handled around CC 3.0 vs CC 4.0

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/39ba1a30-1620-4581-b32f-5b390b72476d)

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/c9966666-99e4-4e60-853d-3b15dbfd9ae0)

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/7ca5399e-a775-4fa4-8d47-4d7a9b3032e7)

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/8c743a36-4918-4fb0-84e6-76845c942b5e)

deployed to QA.

**Comment by fnibbit** [comment]
Created a work associated with creator ID 115, display name Camargo, Braz.  Then marked that creator as inactive.
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/a59c69a4-5f10-4d0a-8599-98aa43bb3a5e)

Inactive creator not included in "search" authority endpoint
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/7605e76f-14d3-41b0-a2f1-5e237e45bed8)

Inactive creator still available at "show" endpoint
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/d7d235ee-f5ca-4231-afe6-87864d60b209)

Inactive creator not included in autocomplete suggestions on a new work
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/b00ec2e7-a98a-4e09-8290-e3da4cda3c90)

Editing a work already associated with an inactive creator and displaying that work results in the creator information saving and displaying as usual.
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/6ddde059-d54e-496e-a074-63593fd3b646)

**Comment by maxkadel** [comment]
deployed to qa on 5/18/2021
