### ISSUE TITLE
Provide a public creator endpoint

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#428]
**STORY**
As a librarian, I would like to make the creator authority publicly accessible, so that outside researchers can see additional authority data.

**ACCEPTANCE**
- [x] There is a public endpoint for the creator authority
- [x] The endpoint is read-only
- [x] The list renders in under 90 seconds (preferably much faster) - add pagination if required to meet this goal

**Comment by maxkadel** [comment]
Two publicly available options, one json, one not:

http://localhost:3000/creators?locale=en
Logged in
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/85d1be3a-fd24-4097-90d6-d04c737eb36c)

Logged out
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/e115999f-4ad1-4f56-8b01-d2b26f46ae56)

http://localhost:3000/authorities/terms/creator_authority
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/9648a341-6ad9-4ca2-9230-fbd45b2a7db0)
