### ISSUE TITLE
Search for alternate names

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#456]
**STORY**
When a creator has multiple name variants, I would like to be able to search with any of them and have results returned showing the primary display name.

**ACCEPTANCE**
When a creator has one or more alternate names created in the creator record
- [x] I can search using all or part of the alternate name
- [x] The system returns all the records for the corresponding creator
- [x] The search results (index) display the primary display name for the creator
- [x] The single item (show) view displays the primary display name for the creator
- [x] The alternate name is not displayed in search results or single item views

**Comment by fnibbit** [comment]
![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/be7ed015-7a73-4aba-ab98-83d9f5cf8929)

![image.png](https://images.zenhubusercontent.com/5e4c418d8f780f6e39f8f8ce/994c69d6-2540-45a4-b578-540ab32fd56b)

on index-alternates-fresh branch
