### ISSUE TITLE
Make display of active status consistent in Manage Creators

### ISSUE THREAD

**Issue by maxkadel** [curationexperts/cypripedium#489]
Index currently does not filter to display only active creators. 

Do we want:
1. Two tabs: active, inactive
2. Three tabs: all, active, inactive
3. Display them all and don't have tabbing

![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/d5ac945d-2958-43b7-8c57-4e7b6351b013)

**Comment by mark-dce** [comment]
I don't think there are going to be many inactive creators - I think it's acceptable to show them all in a single list - i.e. option 3
