### ISSUE TITLE
Return a friendly error on invalid locales

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/cypripedium#502]
**ISSUE**
Application logs are being cluttered by stack dumps from web-crawlers issuing requests with invalid locale codes. 
 Cypripedium currently returns a 500 error and displays "We're sorry but something went wrong" on invalid locale codes.  Rather than throwing an exception, we'd like the application to display a branded error page and return a 406 Not Acceptable response code.

**ACCEPTANCE**
When I submit an invalid locale like https://researchdatabase.minneapolisfed.org/?locale=pluto
- [x] The system returns a branded error page
- [x] The page asks the user to select one of the valid locales from the selector at the upper right of the window
- [x] The server returns a 406 error

**NOTE** We'll want to back port this to Hyrax, but need an immediate term solution in cypripedium first

**CURRENT BEHAVIOR**
![Research_Database - error1](https://user-images.githubusercontent.com/3064318/129057673-e2c0a2cf-5531-436f-9624-435ed7dc0f6a.png)

**DESIRED BEHAVIOR**
![Research_Database - error2](https://user-images.githubusercontent.com/3064318/129057699-e97759b3-416a-4cd9-9d29-0a8ff4d56644.png)

**Comment by maxkadel** [comment]
![image.png](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/9c6a12fc-fcae-4790-9f6a-1525e568a19a)

**Comment by maxkadel** [comment]
![image](https://user-images.githubusercontent.com/45948126/129481803-c35fe843-74d3-4308-948a-099f60c578a0.png)

**Comment by maxkadel** [comment]
PR still needs to be reviewed - passing CI https://github.com/MPLSFedResearch/cypripedium/pull/504
