### ISSUE TITLE
IMPORTER: finish metadata mapping

### ISSUE THREAD

**Issue by bess** [curationexperts/cypripedium#74]
- [ ] create required fields
- [ ] finish metadata import mapping

Data here: 
https://docs.google.com/spreadsheets/d/1Ms2XaewI4wlEiaYAt9OF8-fpJ-Y4wdWDTj4NwhymNaU/edit#gid=1164960854

**Comment by val99erie** [comment]
Closing this story as a duplicate.  See PR 109 and story #115.
